include: package:pedantic/analysis_options.1.9.0.yaml

analyzer:
  exclude:
    - build/**
    - lib/**/*.g.dart
    - test/**/*.g.dart
    - tool/**/*.g.dart
    - lib/main.reflectable.dart
    - lib/**/*.reflectable.dart
    - test/**/*.reflectable.dart
  strong-mode:
    implicit-casts: false

  # enable-experiment:
  #  - non-nullable

linter:
  rules:
    - camel_case_types
