include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  exclude:
    - build/**
    - lib/**/*.g.dart
    - lib/main.reflectable.dart
    - lib/**/*.reflectable.dart
    - test/**/*.g.dart
    - test/**/*.reflectable.dart
  strong-mode:
    implicit-casts: false

linter:
  rules:
    - camel_case_types
